apiVersion: v1
kind: Pod
metadata:
  name: affinity-required-gpu
spec:
  containers:
    - name: nginx
      image: nginx:stable-alpine3.23-perl
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: accelerator
              operator: In
              values:
                - gpu
