apiVersion: v1
kind: Pod
metadata:
  name: no-toleration-pod
  labels:
    app: nginx
    lab: taints
spec:
  containers:
    - name: nginx
      image: nginx:1.25-alpine
      ports:
        - containerPort: 80