apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod
  labels:
    app: nginx
    lab: taints
spec:
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"
  containers:
    - name: nginx
      image: nginx:1.25-alpine
      ports:
        - containerPort: 80