apiVersion: v1
kind: Pod
metadata:
  name: custom-profile-pod
  labels:
    app: scheduler-lab
spec:
  schedulerName: high-priority-scheduler
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.8
