apiVersion: v1
kind: Pod
metadata:
  name: arguments-only-pod
  namespace: cna
spec:
  containers:
    - name: override-args-container
      image: nginx:1.25-alpine
      args: ["echo", "hello from args"]
