apiVersion: v1
kind: Pod
metadata:
  name: sleep-demo-pod
  namespace: cna
spec:
  containers:
    - name: sleep-demo-container
      image: nginx:1.25-alpine
      command: ["sleep"]
      args: ["2600"]
